# Generated by Django 4.0.2 on 2022-02-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.FloatField(blank=True, verbose_name='Вес'),
        ),
    ]
