# Generated by Django 4.0.2 on 2022-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0002_alter_book_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
