# Generated by Django 4.0.2 on 2022-02-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0004_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
