# Generated by Django 4.0.2 on 2022-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0008_alter_comment_book_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='estimate',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
    ]
