# Generated by Django 4.0.2 on 2022-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0013_basket_created_at_basket_quantity_marked_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='marked',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
