# Generated by Django 4.0.2 on 2022-02-17 07:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buybook', '0014_alter_basket_created_at_alter_marked_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('date_of_receipt', models.DateTimeField(default=datetime.datetime(2022, 3, 3, 11, 47, 49, 696319), verbose_name='Дата получения заказа')),
                ('activity', models.BooleanField(default=True, verbose_name='Заказ активен?')),
                ('was_received', models.BooleanField(default=False, verbose_name='Заказ доставлен?')),
                ('total_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Общая стоимость')),
                ('book_id', models.ManyToManyField(related_name='orders_by_book', to='buybook.Book', verbose_name='Книги')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
    ]
