# Generated by Django 4.0.2 on 2022-02-17 14:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0015_book_note_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 21, 27, 435813), verbose_name='Дата получения заказа'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='buybook.book', verbose_name='Книга')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='buybook.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Детали заказов',
                'ordering': ('-order_id', 'book_id'),
            },
        ),
    ]
